Fix collapsing/expanding future node retry
Previously, when trying to collapse (or expand) an non-existing node,
liblarch would remember to do the operation when it sees the node being
added.
However, they pass the liblarch path object instead of the Gtk.TreePath
object, so PyGObject will complain about invalid type:

TypeError: argument path: Expected Gtk.TreePath, but got tuple